config/routes.rb
Lbplayground01::Application.routes.draw do
  get "myboard/index"

  resources :users

  get "liveboard/index"
  get "welcome/index"
  
 
 

  resources :fliers

 match 'signout', to: 'sessions#destroy', as: 'signout'
 match 'addevent', to: 'user_events#create', as: 'addevent'

  root :to=>'liveboard#index', :as => 'liveboard'
 

match 'auth/:provider/callback', to: 'sessions#create'
match 'auth/failure', to: redirect('/')
match 'signout', to: 'sessions#destroy', as: 'signout'
  

end

app/models/flier.rb
class Flier < ActiveRecord::Base
  attr_accessible :id, :title, :description, :endtime, :imageurl, :starttime, 
                  :tagline, :community

  validates :title, :description, :endtime, :imageurl, :starttime, :tagline, :community, :presence => true
  validates :imageurl, :format => {
  :with    => %r{\.(gif|jpg|png)$}i,
  :message => 'must be a URL for GIF, JPG or PNG image.'
}

end


#tests to add: validate that time is in future, that end time is after start-time,
#validate that title and date are unique when put together

app/models/user.rb
class User < ActiveRecord::Base
  
  def self.from_omniauth(auth)
  where(auth.slice(:provider, :fbid)).first_or_initialize.tap do |user|
    user.provider = auth.provider
    user.fbid = auth.uid
    user.fname = auth.info.first_name
    user.lname = auth.info.last_name
    user.image = auth.info.image
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user.save!
  end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    
    helper_method :current_user
end

app/controllers/fliers_controller.rb
class FliersController < ApplicationController
  # GET /fliers
  # GET /fliers.json
  def index
    @fliers = Flier.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fliers }
    end
  end

  # GET /fliers/1
  # GET /fliers/1.json
  def show
    @flier = Flier.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @flier }
    end
  end

  # GET /fliers/new
  # GET /fliers/new.json
  def new
    @flier = Flier.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @flier }
    end
  end

  # GET /fliers/1/edit
  def edit
    @flier = Flier.find(params[:id])
  end

  # POST /fliers
  # POST /fliers.json
  def create
    @flier = Flier.new(params[:flier])

    respond_to do |format|
      if @flier.save
        format.html { redirect_to @flier, notice: 'Flier was successfully created.' }
        format.json { render json: @flier, status: :created, location: @flier }
      else
        format.html { render action: "new" }
        format.json { render json: @flier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fliers/1
  # PUT /fliers/1.json
  def update
    @flier = Flier.find(params[:id])

    respond_to do |format|
      if @flier.update_attributes(params[:flier])
        format.html { redirect_to @flier, notice: 'Flier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @flier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fliers/1
  # DELETE /fliers/1.json
  def destroy
    @flier = Flier.find(params[:id])
    @flier.destroy

    respond_to do |format|
      format.html { redirect_to fliers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/liveboard_controller.rb
class LiveboardController < ApplicationController
  def index
    @fliers = Flier.all
  end
end

app/controllers/myboard_controller.rb
class MyboardController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
     user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to '/'
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/welcome/index.html'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fliers_helper.rb
module FliersHelper
end

app/helpers/liveboard_helper.rb
module LiveboardHelper
end

app/helpers/myboard_helper.rb
module MyboardHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/fliers/_form.html.erb
<%= form_for(@flier) do |f| %>
  <% if @flier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flier.errors.count, "error") %> prohibited this flier from being saved:</h2>

      <ul>
      <% @flier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :tagline %><br />
    <%= f.text_field :tagline %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :starttime %><br />
    <%= f.datetime_select :starttime %>
  </div>
  <div class="field">
    <%= f.label :endtime %><br />
    <%= f.datetime_select :endtime %>
  </div>
  <div class="field">
    <%= f.label :imageurl %><br />
    <%= f.text_field :imageurl %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fliers/edit.html.erb
<h1>Editing flier</h1>

<%= render 'form' %>

<%= link_to 'Show', @flier %> |
<%= link_to 'Back', fliers_path %>

app/views/fliers/index.html.erb
<p id="notice"><%= notice %></p>
<h1> Fliers For Your Community </h1>

<table>
  <% @fliers.each do |flier| %>
  <tr>
    <td><%= image_tag(flier.imageurl) %> </td>
    <td> <%= flier.title  %> </td>
    <td> <%= link_to 'Show', flier %> <br/>
         <%= link_to 'Edit', edit_flier_path(flier) %><br/>
         <%= link_to 'Destroy', flier,
          :confirm => 'Are you sure?',
          :method => :delete %>
    </td>
  </tr>
 <% end %>
</table>

<br/>

<%= link_to 'New Flier', new_flier_path %>

app/views/fliers/new.html.erb
<h1>New flier</h1>

<%= render 'form' %>

<%= link_to 'Back', fliers_path %>

app/views/fliers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b> title:</b>
  <%= @flier. title %>
</p>

<p>
  <b>Tagline:</b>
  <%= @flier.tagline %>
</p>

<p>
  <b>Description:</b>
  <%= @flier.description %>
</p>

<p>
  <b>Starttime:</b>
  <%= @flier.starttime %>
</p>

<p>
  <b>Endtime:</b>
  <%= @flier.endtime %>
</p>

<p>
  <b>Imageurl:</b>
  <%= @flier.imageurl %>
</p>


<%= link_to 'Edit', edit_flier_path(@flier) %> |
<%= link_to 'Back', fliers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Liveboard</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
  <p> Signed in as <%= current_user.fname %> <%=current_user.lname %> <br/>
  <%= link_to 'MyBoard', 'myboard/index.html' %>
  <%= link_to 'Sign Out', 'signout' %>
  </p>
<% else %>
  <p>
    You are not signed in!

  </p>
<% end %>

<%= yield %>

</body>
</html>

app/views/liveboard/index.html.erb
<h1> My Community Liveboard </h1>

<% if notice %>
  <p id="notice">
    <%= notice %>
<% end %>
  </p>


<% @fliers.each do |flier| %>
  <div>
    <%= link_to image_tag(flier.imageurl, { :border => '1' }), flier_path(flier.id) %>
    <h2> <%=  flier.title %> </h2>
    <h3> "<%= flier.tagline %>" </h3>
    <%= button_to 'Add to My Board', 'addevent' %>
    <br/>
  </div>
<% end %>

app/views/myboard/index.html.erb
<h1> Welcome, <%= current_user.fname %> </h1>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :provider %><br />
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :fbid %><br />
    <%= f.number_field :fbid %>
  </div>
  <div class="field">
    <%= f.label :fname %><br />
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br />
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :oauth_expires_at %><br />
    <%= f.datetime_select :oauth_expires_at %>
  </div>
  <div class="field">
    <%= f.label :oauth_token %><br />
    <%= f.text_field :oauth_token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Provider</th>
    <th>Fbid</th>
    <th>Fname</th>
    <th>Lname</th>
    <th>Image</th>
    <th>Oauth expires at</th>
    <th>Oauth token</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.provider %></td>
    <td><%= user.fbid %></td>
    <td><%= user.fname %></td>
    <td><%= user.lname %></td>
    <td><%= user.image %></td>
    <td><%= user.oauth_expires_at %></td>
    <td><%= user.oauth_token %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Provider:</b>
  <%= @user.provider %>
</p>

<p>
  <b>Fbid:</b>
  <%= @user.fbid %>
</p>

<p>
  <b>Fname:</b>
  <%= @user.fname %>
</p>

<p>
  <b>Lname:</b>
  <%= @user.lname %>
</p>

<p>
  <b>Image:</b>
  <%= @user.image %>
</p>

<p>
  <b>Oauth expires at:</b>
  <%= @user.oauth_expires_at %>
</p>

<p>
  <b>Oauth token:</b>
  <%= @user.oauth_token %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<html>
  <h1>Log-in to the Liveboard</h1>
  <%=link_to 'Click here to log-in with your Facebook Account.', '../auth/facebook'%>

</html>